# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-18 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, null=True)),
                ('description', models.CharField(max_length=512, null=True)),
                ('url', models.CharField(max_length=256, null=True)),
                ('mimetype', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
    ]
