# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-10 11:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clip',
            name='name',
        ),
    ]
