# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdviserInvitations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('ID_company', models.IntegerField()),
                ('verification_code', models.CharField(max_length=128)),
                ('is_active', models.BooleanField()),
            ],
        ),
    ]
