# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 18:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_adviserinvitations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adviserinvitations',
            old_name='ID_company',
            new_name='IdCompany',
        ),
        migrations.RenameField(
            model_name='adviserinvitations',
            old_name='is_active',
            new_name='isActive',
        ),
        migrations.RenameField(
            model_name='adviserinvitations',
            old_name='verification_code',
            new_name='verificationCode',
        ),
        migrations.AddField(
            model_name='adviserinvitations',
            name='creationTime',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 4, 18, 3, 2, 511925, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adviserinvitations',
            name='usedTime',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 4, 18, 3, 20, 940262, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
