# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-09 12:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_adviseruser_id_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adviserinvitations',
            old_name='ID_company',
            new_name='id_company',
        ),
        migrations.RenameField(
            model_name='adviseruser',
            old_name='ID_company',
            new_name='IdCompany',
        ),
        migrations.AddField(
            model_name='adviserinvitations',
            name='creation_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 9, 12, 5, 41, 437991, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adviserinvitations',
            name='used_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adviserinvitations',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
