# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-07 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20160804_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adviserinvitations',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='adviserinvitations',
            name='usedTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
