# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-08 07:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20160807_1119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adviserinvitations',
            old_name='creationTime',
            new_name='creation_time',
        ),
        migrations.RenameField(
            model_name='adviserinvitations',
            old_name='IdCompany',
            new_name='id_company',
        ),
        migrations.RenameField(
            model_name='adviserinvitations',
            old_name='isActive',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='adviserinvitations',
            old_name='usedTime',
            new_name='used_time',
        ),
        migrations.RenameField(
            model_name='adviserinvitations',
            old_name='verificationCode',
            new_name='verification_code',
        ),
    ]
