# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-09 10:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20160807_1111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adviseruser',
            old_name='IdCompany',
            new_name='id_company',
        ),
    ]
