# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-09 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20160809_1054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adviserinvitations',
            old_name='creationTime',
            new_name='creation_time',
        ),
        migrations.RenameField(
            model_name='adviserinvitations',
            old_name='IdCompany',
            new_name='id_company',
        ),
        migrations.RenameField(
            model_name='adviserinvitations',
            old_name='verificationCode',
            new_name='verification_code',
        ),
        migrations.RemoveField(
            model_name='adviserinvitations',
            name='isActive',
        ),
        migrations.RemoveField(
            model_name='adviserinvitations',
            name='usedTime',
        ),
        migrations.AddField(
            model_name='adviserinvitations',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='adviserinvitations',
            name='used_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
