# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-10 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20160809_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adviseruser',
            name='avatar',
            field=models.URLField(default='default-user-logo.png'),
        ),
    ]
