# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-12 11:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20160810_1130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adviseruser',
            old_name='id_company',
            new_name='company_id',
        ),
    ]
