# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-11 14:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20160810_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adviseruser',
            name='id_company',
        ),
        migrations.AddField(
            model_name='adviseruser',
            name='ID_company',
            field=models.IntegerField(),
            preserve_default=False,
        ),
    ]
