# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-16 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_auto_20160812_1158'),
        ('company', '0003_auto_20160811_0623')
    ]

    operations = [
        migrations.AlterField(
            model_name='adviseruser',
            name='id_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company'),
        ),
    ]
