# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-16 12:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_auto_20160816_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adviserinvitations',
            name='id_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company'),
        ),
    ]
