# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-09 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_logo', models.URLField(unique=True)),
                ('company_name', models.CharField(max_length=200, unique=True)),
                ('company_mail', models.EmailField(max_length=254, unique=True)),
                ('company_phone', models.CharField(max_length=50, unique=True)),
                ('company_address', models.CharField(max_length=200, unique=True)),
                ('administrator', models.IntegerField()),
            ],
        ),
    ]
