# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-27 17:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20160826_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='administrator',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.AdviserUser'),
        ),
    ]
