# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-05 12:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20160927_1741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='company_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='company_logo',
            new_name='logo',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='company_mail',
            new_name='mail',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='company_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='company_phone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='company_zipcode',
            new_name='zipcode',
        ),
    ]
