# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-25 07:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0002_auto_20160825_0708'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdviserProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('id_template', models.IntegerField(default=1)),
                ('id_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company')),
            ],
        ),
    ]
