# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-27 07:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adviserproject',
            name='id_template',
        ),
        migrations.AddField(
            model_name='adviserproject',
            name='project_template',
            field=models.TextField(default=datetime.datetime(2016, 8, 27, 7, 44, 10, 242506, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
