# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-04 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0004_auto_20160823_1042'),
        ('projects', '0002_auto_20160827_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='adviserproject',
            name='player',
            field=models.ManyToManyField(to='player.Player'),
        ),
    ]
