# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-01 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20160827_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adviserproject',
            name='description',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='adviserproject',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
