# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-02 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20160901_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adviserproject',
            name='project_template',
            field=models.TextField(blank=True, null=True),
        ),
    ]
