# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-17 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20160902_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='adviserproject',
            name='project_hash',
            field=models.TextField(blank=True, null=True),
        ),
    ]
