# -*- coding: utf-8 -*-

# Generated by Django 1.9.8 on 2016-09-02 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('mac_address', models.CharField(max_length=17)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
