# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-01 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
