# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-15 03:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='description',
            new_name='player_description',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='mac_address',
            new_name='player_mac_address',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='name',
            new_name='player_name',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='status',
            new_name='player_status',
        ),
    ]
