# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-12 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_player_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='hashsum',
            field=models.CharField(max_length=512, blank=True, null=True),
        ),
    ]
