# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-17 09:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_auto_20161012_0928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='hashsum',
        ),
    ]
