# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-17 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='XmlTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=128, verbose_name='name')),
                ('template_content', models.TextField(verbose_name='content')),
            ],
            options={
                'verbose_name': 'Xml Template',
                'verbose_name_plural': 'Xml Templates',
            },
        ),
    ]
